### ISSUE TITLE
sublist.pl does not consider cases where an element has been removed with it's corresponding neighbours still present in the sublist

### ISSUE THREAD

**Issue by HarshSulakhe** [AryamanBhagat/CS-F214-A1#2]
`suffix(X,L)` will give:
```
X = [ L1, L2, ......, Ln]
.
.
.
X = [ ]
```
Consider the case L = [1,2,3,4,5,6]
A = [2,3,5]

From the given values of X, there is no X such that there would exist a list which on being appended to A would give X. (prefix(A, X) evaluates to no)

Please correct me if I'm mistaken.

**Comment by HarshSulakhe** [comment]
Sent pull request resolving this issue

**Comment by jshreyans** [comment]
So we seem to have misinterpreted the question. We thought sublist means a list of elements in the same order as they appear in the original list. So the example you gave was not considered. 
By our logic, if A = [1,2,3,4]
then X = [1,2] would be a sublist but X=[1,3] wouldn't. But apparently, that is the way it should be.
So the code does need correction.

**Comment by HarshSulakhe** [comment]
Check the PR, I have tried to correct it to the best of my knowledge.
